import { useEffect, useMemo, useState } from 'react';

type Category = 'all' | 'insider' | 'institutional' | 'political' | 'macro';
type Opportunity = { id: string; category: Exclude<Category, 'all'>; badge: string; asset: string; title: string; subtitle: string; date: string; source: string; sourceUrl: string; confidence: 'alta' | 'média' | 'contexto'; evidence: string; thesis: string; whyNow: string; risks: string; tags: string[] };

const opportunities: Opportunity[] = [
  { id: 'civb', category: 'insider', badge: 'SEC · FORM 4', asset: 'CIVB', title: 'Civista Bancshares — compra do presidente', subtitle: 'Compra aberta de ações por Charles A. Parcher', date: '23/09/2026', source: 'SEC EDGAR', sourceUrl: 'https://www.sec.gov/edgar/browse/?CIK=0001075632&owner=exclude', confidence: 'média', evidence: 'Charles A. Parcher comprou 400 ações a US$ 26,75, aproximadamente US$ 10.700. Confirme no Form 4 completo o código da transação e as notas.', thesis: 'Compra voluntária feita por executivo operacional. É um ponto de partida para investigar valuation, crédito, margem financeira e retorno sobre patrimônio.', whyNow: 'Bancos regionais podem se beneficiar se os juros estabilizarem e a curva favorecer a margem financeira.', risks: 'Compra pequena e sem confirmação de cluster. Crédito, inadimplência e regulação podem superar o sinal.', tags: ['CIVB', 'banco regional', 'insider'] },
  { id: 'gam', category: 'insider', badge: 'SEC · FORM 4', asset: 'GAM', title: 'General American Investors — compra do chairman', subtitle: 'Compra de 10.000 ações por Spencer Davidson', date: '23/09/2026', source: 'SEC EDGAR', sourceUrl: 'https://www.sec.gov/edgar/browse/?CIK=0000040545&owner=exclude', confidence: 'média', evidence: 'Spencer Davidson comprou 10.000 ações a US$ 22,75, aproximadamente US$ 227.500.', thesis: 'O valor material pode indicar convicção no desconto entre o closed-end fund e o NAV. Avalie desconto, distribuição, alavancagem e liquidez.', whyNow: 'Closed-end funds podem reprecificar quando o desconto ao NAV se reduz e a carteira melhora.', risks: 'O desconto pode permanecer por anos e a carteira continua exposta ao mercado acionário.', tags: ['GAM', 'closed-end fund', 'NAV'] },
  { id: 'dhi', category: 'institutional', badge: 'BERKSHIRE · 13F', asset: 'DHI', title: 'Berkshire Hathaway — nova posição em D.R. Horton', subtitle: 'Entrada no setor de construção residencial', date: 'Filing 14/08/2026 · posição em 30/06', source: 'SEC EDGAR', sourceUrl: 'https://www.sec.gov/Archives/edgar/data/1067983/000119312526352200/d498521d13fhr.htm', confidence: 'contexto', evidence: 'O 13F-HR da Berkshire, protocolado em 14/08/2026 e referente a 30/06/2026, reportou DHI como nova posição.', thesis: 'A entrada sugere preferência institucional por uma construtora de escala, mas precisa ser confrontada com juros hipotecários, margem e cancelamentos.', whyNow: 'Se os juros longos caírem sem recessão, acessibilidade e volume podem melhorar.', risks: 'O 13F é atrasado e não revela preço ou data da compra. A Berkshire pode já ter alterado a posição.', tags: ['DHI', 'Berkshire', 'housing'] },
  { id: 'avgo', category: 'political', badge: 'STOCK ACT · HOUSE', asset: 'AVGO', title: 'Rick Allen — compra de Broadcom', subtitle: 'Compra declarada na faixa de US$ 1.001–15.000', date: 'Trade 12/08/2026 · filing 22/09/2026', source: 'House Clerk', sourceUrl: 'https://disclosures-clerk.house.gov/PublicDisclosure/FinancialDisclosure', confidence: 'contexto', evidence: 'O disclosure atribuído a Rick W. Allen registra compra de AVGO em 12/08/2026 na faixa de US$ 1.001 a US$ 15.000.', thesis: 'AVGO expõe o investidor a networking, semicondutores e data centers. É uma pista de pesquisa, não prova de informação privilegiada.', whyNow: 'A tese depende de capex de IA, poder de precificação e conversão de caixa.', risks: 'Faixa ampla e atraso de 41 dias. Confirme o PDF e a titularidade antes de interpretar.', tags: ['AVGO', 'semicondutores', 'Congresso'] },
  { id: 'tsm', category: 'political', badge: 'STOCK ACT · HOUSE', asset: 'TSM', title: 'Rick Allen — compra de Taiwan Semiconductor', subtitle: 'Exposição à cadeia global de chips', date: 'Trade 12/08/2026 · filing 22/09/2026', source: 'House Clerk', sourceUrl: 'https://disclosures-clerk.house.gov/PublicDisclosure/FinancialDisclosure', confidence: 'contexto', evidence: 'O mesmo disclosure registra compra de TSM na faixa de US$ 1.001 a US$ 15.000 em 12/08/2026.', thesis: 'TSM acompanha fabricação avançada e computação de IA. Analise capex, utilização de fabs e risco geopolítico.', whyNow: 'A demanda por nós avançados pode sustentar crescimento, mas parte da narrativa pode já estar precificada.', risks: 'Disclosure tardio, faixa imprecisa, risco Taiwan-China e câmbio.', tags: ['TSM', 'chips', 'geopolítica'] },
  { id: 'macro', category: 'macro', badge: 'TOP-DOWN · EUA', asset: 'TLT · XLF · XLP · DHI', title: 'Expansão madura com inflação persistente', subtitle: 'Crescimento moderado, emprego estável e juros elevados', date: 'Leitura de setembro/2026', source: 'Fed · BLS · BEA', sourceUrl: 'https://www.federalreserve.gov/monetarypolicy/fomcprojtabl20260916.htm', confidence: 'contexto', evidence: 'SEP de 16/09/2026: PIB de 2,3% em 2026, desemprego de 4,1%, PCE de 3,7% e fed funds de 4,1% no fim do ano.', thesis: 'Expansão madura: duration se a desinflação continuar, defensivos se o crescimento perder força e financeiros/valor enquanto os juros permanecerem altos.', whyNow: 'TLT pode ganhar com queda de juros; XLP/XLV oferecem estabilidade; XLF captura juros altos; DHI depende de queda das taxas hipotecárias.', risks: 'Inflação persistente prejudica duration; recessão prejudica bancos e construtoras; valuation pode anular a tese.', tags: ['PIB 2,3%', 'desemprego 4,1%', 'PCE 3,7%'] }
];
const categories: { id: Category; label: string }[] = [{ id: 'all', label: 'Todos' }, { id: 'insider', label: 'Insiders' }, { id: 'institutional', label: 'Grandes investidores' }, { id: 'political', label: 'Políticos' }, { id: 'macro', label: 'Macro' }];
function nextAnalysis() { const date = new Date(); date.setHours(19, 0, 0, 0); if (date.getTime() <= Date.now()) date.setDate(date.getDate() + 1); return date; }
function countdown(ms: number) { const total = Math.max(0, Math.floor(ms / 1000)); return `${String(Math.floor(total / 3600)).padStart(2, '0')}:${String(Math.floor((total % 3600) / 60)).padStart(2, '0')}:${String(total % 60).padStart(2, '0')}`; }
function confidence(value: Opportunity['confidence']) { return value === 'alta' ? 'Alta' : value === 'média' ? 'Média' : 'Contexto'; }

function Header({ now, next }: { now: number; next: Date }) { return <header className="topbar"><div className="brand-wrap"><img className="brand-logo" src={`${import.meta.env.BASE_URL}logo.svg`} alt="Trendgram" /></div><div className="update-clock"><span className="update-label">PRÓXIMA ANÁLISE · 19H</span><strong>{countdown(next.getTime() - now)}</strong></div></header>; }

export default function App() {
  const [category, setCategory] = useState<Category>('all');
  const [openId, setOpenId] = useState<string | null>(null);
  const [now, setNow] = useState(Date.now());
  const [next, setNext] = useState(nextAnalysis);
  const visible = useMemo(() => category === 'all' ? opportunities : opportunities.filter((item) => item.category === category), [category]);
  const selected = opportunities.find((item) => item.id === openId);
  useEffect(() => { const timer = window.setInterval(() => { const value = Date.now(); setNow(value); if (value >= next.getTime()) setNext(nextAnalysis()); }, 1000); return () => window.clearInterval(timer); }, [next]);
  useEffect(() => { window.scrollTo({ top: 0, behavior: 'smooth' }); }, [openId]);

  if (selected) return <div className="app-shell detail-shell"><Header now={now} next={next} /><main className="detail-page"><button className="back-button" type="button" onClick={() => setOpenId(null)}><span>←</span> Voltar para oportunidades</button><section className="detail-hero"><div className="detail-asset">{selected.asset}</div><div className="detail-hero-copy"><div className="badge-row"><span className="status-dot" /><span>{selected.badge}</span><span className="tag">{confidence(selected.confidence)}</span></div><h1>{selected.title}</h1><p>{selected.subtitle}</p></div></section><section className="detail-metrics"><div><span>Data do evento</span><strong>{selected.date}</strong></div><div><span>Categoria</span><strong>{selected.category}</strong></div><div><span>Origem</span><strong>{selected.source}</strong></div></section><section className="detail-grid"><article className="detail-card evidence-card"><p className="eyebrow">01 · evidência</p><h2>O que foi encontrado</h2><p>{selected.evidence}</p></article><article className="detail-card thesis-card"><p className="eyebrow">02 · tese</p><h2>Por que pode ser oportunidade</h2><p>{selected.thesis}</p></article><article className="detail-card timing-card"><p className="eyebrow">03 · momento</p><h2>Por que agora</h2><p>{selected.whyNow}</p></article><article className="detail-card risk-card"><p className="eyebrow">04 · riscos</p><h2>O que pode invalidar</h2><p>{selected.risks}</p></article></section><section className="detail-footer"><div><p className="eyebrow">diligência</p><h2>Confirmação no documento primário</h2><p>Esta página organiza a hipótese. Antes de tomar qualquer decisão, confirme data, notas, titularidade, código da transação e contexto no documento original.</p></div><a className="source-link" href={selected.sourceUrl} target="_blank" rel="noreferrer">Abrir {selected.source} <span>↗</span></a></section></main></div>;

  return <div className="app-shell"><Header now={now} next={next} /><main className="feed-panel feed-page"><div className="feed-header"><div><p className="eyebrow">research feed</p><h2>Oportunidades encontradas</h2></div><span className="live-pill">FONTES OFICIAIS</span></div><div className="quote-status"><span className="status-dot" />Evidências específicas · análise diária às 19h</div><div className="filters">{categories.map((item) => <button key={item.id} type="button" className={item.id === category ? 'filter active' : 'filter'} onClick={() => setCategory(item.id)}>{item.label}</button>)}</div><div className="opportunity-grid">{visible.map((item) => <button key={item.id} type="button" className="post opportunity-card" onClick={() => setOpenId(item.id)}><div className="post-topline"><div className="avatar">{item.asset.slice(0, 2)}</div><div className="post-meta"><div className="line-1"><strong>{item.asset}</strong><span className="tag">{confidence(item.confidence)}</span></div><span className="market-name">{item.badge} · {item.date}</span></div><span className="card-arrow">↗</span></div><div className="post-copy"><h3>{item.title}</h3><p>{item.subtitle}</p></div><div className="trade-strip"><span>Tipo<strong>{item.category === 'macro' ? 'Ciclo' : 'Evento'}</strong></span><span>Fonte<strong>Primária</strong></span><span>Abrir<strong>Detalhes</strong></span></div></button>)}</div></main></div>;
}
